export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
// export const GET_PRODUCTS = "GET_PRODUCTS";S